### PR TITLE
Remove openbox, using gnome now

### PR DESCRIPTION
**Pull request by Samsagax**

### CODE REVIEW

**Comment by alkazar** [comment]
Still needed for the "switch window mode" chimera action.

**Comment by Samsagax** [comment]
> Still needed for the "switch window mode" chimera action.

Mhhh... we should change that to use mutter instead I think, or just switch to GNOME.

**Comment by alkazar** [comment]
The feature is useful as is for BPM. Once BPM is out of the picture this can be removed.
Alternatively, we could just drop this feature and tell people: go use the desktop.
The only problem is it may be difficult for some users to do that when the option to switch to desktop does not work in BPM.

**Comment by Samsagax** [comment]
What about adding two shortcuts to steam: one for entering Desktop and one for switching to Gamescope/GampeadUI?

**Comment by alkazar** [comment]
> What about adding two shortcuts to steam: one for entering Desktop and one for switching to Gamescope/GampeadUI?

Not sure I want to bother. Once BPM is out of the picture there won't be any need for that.
Closing for now.

**Pull request closed without merging**
