### PR TITLE
Update manifest for rclone

### PR DESCRIPTION
**Pull request by mdeguzis**
https://archlinux.org/packages/extra/x86_64/rclone/

Having rclone built in is super handy for making cloud saves/scripting to backup my game saves and other files.

### CODE REVIEW

**Comment by pastaq** [comment]
How big is the install on disk?

**Comment by alkazar** [comment]
The package is 88 MB installed. It feels a bit too big for the limited use case.

**Comment by ruineka** [comment]
Rclone is extremely useful and is used with emudeck to sync saves to the cloud. I'd argue that this is totally worth it.

**Comment by ruineka** [comment]
> Emudeck doesn't come with a bundled rclone binary?

I'd have to check.

**Comment by alkazar** [comment]
It would have to unless SteamOS includes it?

**Comment by npaladin2000** [comment]
While I agree it's really handy to have it's also easy enough to just drop the binary in your home directory and run it from there.

**Comment by pastaq** [comment]
Before I close this, are we in consensus that we don't want to include it for now?

**Comment by alkazar** [comment]
I think so?

**Pull request closed without merging**
