### PR TITLE
Add tools to update device firmware

### PR DESCRIPTION
**Pull request by majamee**
I noticed that in the current version of Chimera OS is no method present to update device firmware. Therefore I added "gnome-firmware" to the manifest of ChimeraOS. This tool should allow every user from the desktop session to easily and safely update their device firmware. If you do not wan't to include a GUI tool please at least include the underlying "fwupd" tool instad of "gnome-firmware".

### CODE REVIEW

**Comment by alkazar** [comment]
If we include fwupd I think Gnome Software can handle firmware updates? If so, we wouldn't need to include a separate tool just for that.

**Comment by alkazar** [comment]
Literally as I typed my previous comment, Gnome Software on my desktop popped up with a firmware update notification.

**Comment by majamee** [comment]
Then it's perfect to just include fwupd. Shall I adjust the PR or do you want to?

**Comment by majamee** [comment]
@alkazar done :)

**Comment by Samsagax** [comment]
LGTM

**Pull request merged**
