### PR TITLE
razer: allow control of such hardware

### PR DESCRIPTION
**Pull request by NeroReflex**
Razer is well-known into desktop PC gaming and also makes some latops. Add the required dkms kernel module and daemon to allow configuring those devices. Multiple frontends are available for the user to choose from and none is included.

### CODE REVIEW

**Comment by pastaq** [comment]
What is the impact on file size?

**Comment by NeroReflex** [comment]
> What is the impact on file size?

Not much: I tested in a fork that uses plasm6 and that alone uncovered the need of not tar'ing the image. End result was oversized and release failed. I removed this package but the release still was oversized. Removed ardour (keeping openrazer-meta) and release was about 2GB. So it occupies surely less than ardour.

**Comment by pastaq** [comment]
```
[gamer@ayaneo2s ~]$ sudo pacman -Sy openrazer-daemon
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 multilib is up to date
resolving dependencies...
looking for conflicting packages...

Packages (14) dbus-python-1.3.2-2  dkms-3.0.12-1  gc-8.2.6-1  gcc-13.2.1-5  guile-3.0.9-1  libisl-0.26-1  libmpc-1.3.1-1  make-4.4.1-2  openrazer-driver-dkms-3.7.0-1  patch-2.7.6-10  python-daemonize-2.5.0-6
              python-setproctitle-1.3.3-1  xautomation-1.09-5  openrazer-daemon-3.7.0-1

Total Download Size:    47.52 MiB
Total Installed Size:  248.28 MiB
```

**Comment by NeroReflex** [comment]
> ```
> [gamer@ayaneo2s ~]$ sudo pacman -Sy openrazer-daemon
> :: Synchronizing package databases...
>  core is up to date
>  extra is up to date
>  multilib is up to date
> resolving dependencies...
> looking for conflicting packages...
> 
> Packages (14) dbus-python-1.3.2-2  dkms-3.0.12-1  gc-8.2.6-1  gcc-13.2.1-5  guile-3.0.9-1  libisl-0.26-1  libmpc-1.3.1-1  make-4.4.1-2  openrazer-driver-dkms-3.7.0-1  patch-2.7.6-10  python-daemonize-2.5.0-6
>               python-setproctitle-1.3.3-1  xautomation-1.09-5  openrazer-daemon-3.7.0-1
> 
> Total Download Size:    47.52 MiB
> Total Installed Size:  248.28 MiB
> ```

That is also counting GCC, dkms and make tools that we remove from the image before shipping

**Comment by NeroReflex** [comment]
@pastaq impact is something less of 5MB of mostly-text files that will compress quite well by btrfs (see the other PR) and xz before releasing

**Pull request merged**
