### PR TITLE
Create 99-hidapi.rules for Nintendo Joy-Con and Pro Controller

### PR DESCRIPTION
**Pull request by cwalker**
This will give read and write permissions to hidraw-devices
Such as Nintendo Joy-Con and Pro Controller

### CODE REVIEW

**Comment by alkazar** [comment]
I was just doing some research on this and it seems like `hid-hidraw` and `hid-nintendo` conflict.

Shouldn't we be using `hid-nintendo` ?

**Comment by cwalker** [comment]
Yes, hid-nintendo works flawesly, except gyro.
With this rule, gyro works.
As variant, just add this aur package: https://aur.archlinux.org/packages/nintendo-udev

**Comment by Samsagax** [comment]
If already is an AUR package I would go for that route. The `nintendo-udev` package rule seems well-written and very device specific so looks good to me

**Comment by alkazar** [comment]
Closed in favor of https://github.com/ChimeraOS/chimeraos/pull/325

Thanks for bringing this to our attention!

**Pull request closed without merging**
