### PR TITLE
added tauri apps prerequisites

### PR DESCRIPTION
**Pull request by tsimouris**

### CODE REVIEW

**Comment by tsimouris** [comment]
There should have been some more packages included, my bad. As per the reasoning, I've been working on these two projects:

- https://github.com/tsimouris/youtube-tv
- https://github.com/tsimouris/twitch-tv

Just need to configure the icons now and work on the tauri bundrer, for flatpak support that is. For now though AppImages can be used.

**Comment by alkazar** [comment]
If the flatpak issue is resolved then we won't these packages?

**Comment by tsimouris** [comment]
True, the solution is rather temporary till the flatpak bundler is ready; at that point these should be part of the flatpak dependencies

**Comment by alkazar** [comment]
Looks like AppImage might also be a solution? In any case, I don't think we need native support for this. Most people will want to use Flatpak, and that would be the preferred solution.

**Pull request closed without merging**
