### PR TITLE
Add sunshine game streaming tool

### PR DESCRIPTION
**Pull request by ruineka**
This has been requested many times in the discord.

### CODE REVIEW

**Comment by pastaq** [comment]
Does this actually work for streaming Wayland? I saw they still had issues open for it on their GitHub when I changed a couple days ago.

**Comment by maddox** [comment]
It's been working amazingly for me. In fact, it's been the best game streaming I've experienced. ChimeraOS's nature lends a lot to this.

 I manually installed the Flatpack available in Sunshine's releases on GitHub.

I can even start the `desktop-xorg` via ssh and use Moonlight to remotely manage it via Desktop Mode.

1. stop Sunshine
2. `chimera-session desktop-xorg`
3. start Sunshine
4. connect with Moonlight

to return to Game Mode:

1. stop Sunshine
2. `chimera-session gamepadui`
3. start Sunshine

**Comment by schyhub** [comment]
> Does this actually work for streaming Wayland? I saw they still had issues open for it on their GitHub when I changed a couple days ago.

It has been working normally on gamescope on ChimeraOS and my wayland KDE desktop. IIRC, it uses KSM when captures on Wayland, which works.

**Comment by alkazar** [comment]
Sorry, but we can't add every niche package that is requested.
This looks like it adds over 120 MB to the install size and the majority of people will never use this.

I tried to at least check this out, but the package build is failing.

**Comment by ruineka** [comment]
> Sorry, but we can't add every niche package that is requested.
> This looks like it adds over 120 MB to the install size and the majority of people will never use this.
> 
> I tried to at least check this out, but the package build is failing.

That's fair, thats why I open PR rather than just add stuff.

**Comment by schyhub** [comment]
Also would be understandable. The old sushine use just some package but now pull in custom ffmpeg and other stuff. I didn't also realize it blown up that big in total now

**Pull request closed without merging**
